package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("result generated by:"+
        Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run();//normal execution->always the main thread
        t1.start();//muiti threading->t-0,t-1& so on
        //start() internally calls run()
        //thread cannot be started twice
    }
}
